name: Go Linter

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
    paths:
      - '**/*.go'
      - 'go.mod'
      - '.github/workflows/golangci-lint.yml'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
